name: Build Test and Doc
on: 
  push:
    branches:
      - build-workflow
jobs:
  build-test-doc:
    name: build test doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          repository: michaelchin/geoserver-pyadm
          token: ${{ secrets.GH_PAGE_COMMIT_TOKEN }}
          path: main

      - name: Checkout github pages branch
        uses: actions/checkout@v2
        with:
          repository: michaelchin/geoserver-pyadm
          ref: gh-pages
          token: ${{ secrets.GH_PAGE_COMMIT_TOKEN }}
          path: gp-pages
       
      - name: Update websites
        run: | 
          chmod +x ./main/scripts/build-workflow.sh
          cd main
          ./scripts/build-workflow.sh
        env:
          GITHUB_TOKEN: '${{secrets.GH_PAGE_COMMIT_TOKEN}}'

